version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    environment:
      - API_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
